src/comms/table-controller.ts

fixes: https://github.com/withthegrid/platform-docs/issues/5, https://github.com/withthegrid/platform-docs/issues/4

fix: require query property to be defined on SDK calls

---

src/routes/command-type/routes.ts
src/routes/command/routes.ts
src/routes/device-type/routes.ts
src/routes/device/routes.ts
src/routes/environment/routes.ts
src/routes/issue-comment/routes.ts
src/routes/issue/routes.ts
src/routes/label/routes.ts
src/routes/quantity/routes.ts
src/routes/report-type/routes.ts
src/routes/report/routes.ts
src/routes/subscription/routes.ts
src/routes/supplier-certificate/routes.ts
src/routes/supplier-report-type/routes.ts
src/routes/supplier-webhook/routes.ts
src/routes/supplier/routes.ts
src/routes/user/routes.ts

fixes: https://github.com/withthegrid/platform-docs/issues/6

fix: export deleteRoute as delete for controller routes

---

src/models/measurement.ts
src/routes/measurement/index.ts
src/routes/measurement/routes.ts
src/routes/measurement/set-anomalous-user.ts
src/routes/measurement/setAnomalousUser.ts

Add new routes and models for anomaly detection

Initialize anomaly detection branch

---

src/models/quantity.ts
src/routes/quantity/add.ts
src/routes/quantity/update.ts
src/routes/report-type/add.ts
src/routes/report-type/update.ts

added default thresholds into quantity interface and route schemas for both environments

feat: default thresholds for quantities

---

src/models/export-request.ts
src/routes/settings/add-export.ts
src/routes/settings/find-export-request.ts

* added name, description fields to MeasurementFilterContent interface, added MeasurementFilterContentByHashId interface to settings.add-export route
* reusing contentSchemaAlternatives

Feat platform 563 create export request by measurement filter hashid

---

src/routes/device-type/find.ts

changed rights of device-type.find route

feat: get device types of client

---

src/models/export-request.ts
src/routes/measurement-filter/add.ts
src/routes/measurement-filter/update.ts
src/routes/measurement/find.ts
src/routes/settings/add-export.ts

increased allowed count of quantityHashIds at related schemas

feat: increase quantities count

---

src/comms/controller.ts
src/models/chart.ts
src/models/index.ts
src/models/measurement.ts
src/routes/chart/get-panel.ts
src/routes/chart/get.ts
src/routes/chart/index.ts
src/routes/chart/routes.ts
src/routes/chart/update-panel.ts
src/routes/index.ts
src/routes/routes.ts

relates to withthegrid/platform-client#60

Feat platform client 60 graph improvements

---

src/routes/graph/find-pin-quantities.ts
src/routes/graph/get-pin-quantities.ts
src/routes/graph/index.ts
src/routes/graph/routes.ts

added `graph.findPinQuantities` route

feat(graph.findPinQuantities):

---

src/routes/graph/set-threshold.ts

request body `thresholds` property can be null

feat(graph.setThreshold):

---

src/models/chart.ts
src/models/device-type.ts
src/models/quantity.ts
src/routes/chart/update-panel.ts
src/routes/device-type/add.ts
src/routes/device-type/update.ts
src/routes/quantity/add.ts
src/routes/quantity/update.ts

* added `color` to the `Quantity` model and routes
* made `series[].color` nullabe everywhere at charts

feat(device-type,quantity,chart): quantity color

---

src/routes/graph/set-threshold.ts

fix(graph/set-threshold): right types for Response.hashId

---

src/routes/report-type/add.ts
src/routes/report-type/update.ts

Updated `report-type.add`, `report-type.update` routes
Fixes withthegrid/platform#584

feat(report-type/add,report-type/update): added color property into report-type routes

---

src/comms/table-controller.ts
src/models/analytics-query.ts
src/models/index.ts
src/routes/analytics/find.ts
src/routes/analytics/index.ts
src/routes/analytics/routes.ts
src/routes/index.ts
src/routes/routes.ts

part of withthegrid/platform#572

feat: analytics route

---

package.json
src/models/log.ts
src/routes/settings/find-log.ts

Related PRs:
https://github.com/withthegrid/platform-client/pull/494
https://github.com/withthegrid/platform/pull/669

Feat 421 audit log generic

---

src/models/index.ts
src/models/pin-link.ts
src/routes/graph/add-edge-to-pin.ts
src/routes/graph/get-pin-group.ts

I've removed pin-links models to fast, we need it yet for frontend, to switch without problems

feat: put back pin links (temporary)

---

src/routes/graph/add-pin-group.ts
src/routes/graph/update-pin-group.ts

part of withthegrid/platform#683

feat: gridName in graph.addPinGroup and graph.updatePinGroup

---

src/routes/graph/find-grid.ts

Related PRs:
https://github.com/withthegrid/platform/pull/687
https://github.com/withthegrid/platform-client/pull/505

#454 - Added notifications level for group

---

src/routes/measurement/find.ts

Part of withthegrid/platform-client#523

feat: added edgeName to sortBy values for meauserment.find route

---

src/models/analytics-query.ts

Part of withthegrid/platform#681

feat: added inGrid comparison type to analytics query

---

src/models/analytics-query.ts

Part of withthegrid/platform#697

feat: added isNamedRange comparison type to analytics query

---

src/models/analytics-query.ts

Part of withthegrid/platform#680

feat: analytics constraints right hand references

---

package-lock.json
src/models/fields/base-field-configuration.ts

Part of withthegrid/platform-client#562

feat: added allowNull property to BaseFieldConfiguration

---

src/comms/table-controller.ts
src/routes/analytics/index.ts
src/routes/command-type/index.ts
src/routes/command/index.ts
src/routes/device-type/index.ts
src/routes/device/index.ts
src/routes/environment/index.ts
src/routes/graph/index.ts
src/routes/issue/index.ts
src/routes/label/index.ts
src/routes/measurement-filter/index.ts
src/routes/measurement/index.ts
src/routes/quantity/index.ts
src/routes/report-type/index.ts
src/routes/report/index.ts
src/routes/settings/index.ts
src/routes/subscription/index.ts
src/routes/supplier-activity/index.ts
src/routes/supplier-certificate/index.ts
src/routes/supplier-report-type/index.ts
src/routes/supplier-webhook/index.ts
src/routes/supplier/index.ts
src/routes/user/index.ts

part of withthegrid/platform#768

feat: removed lastValue parameters

---

src/models/fields/base-field-configuration.ts

if defaultValue is set.
Fixes withthegrid/platform-client#724

fix: allowNull is not required

---

src/models/analytics-panel.ts
src/models/index.ts
src/routes/analytics/add-panel.ts
src/routes/analytics/update-panel.ts

Part of withthegrid/platform-client#621

feat: grid layout for analytics panel

---

src/models/environment.ts
src/routes/environment/update.ts

Is required for https://github.com/withthegrid/platform-client/pull/746
Is related to https://github.com/withthegrid/platform-client/pull/746

#664 - Added default graph range for environment

---

src/models/environment.ts
src/routes/environment/update.ts

Part of withthegrid/platform#377

feat(envirnoment): added measurements expiration period

---

src/models/analytics-panel.ts
src/routes/analytics/add-panel.ts
src/routes/analytics/update-panel.ts

Is required for [#804](https://github.com/withthegrid/platform-client/pull/804)
Is required for [#887](https://github.com/withthegrid/platform/pull/887)

feat: add subtitle to analytics widget

---

src/routes/index.ts
src/routes/routes.ts
src/routes/suggestions/find.ts
src/routes/suggestions/index.ts
src/routes/suggestions/routes.ts

Part of withthegrid/platform-client#770

feat(routes): suggestions.find

---

src/models/analytics-visualisation.ts

Is required for https://github.com/withthegrid/platform-client/pull/798

#854 - Added showAllXAxisLabels to analytics visualisation

---

src/models/analytics-query.ts

Part of withthegrid/platform#863
I think I've seen that backwards compatible changes in this repository do not update the version?

feat: only show x last measurements per port per quantity

---

src/models/analytics-query.ts

refs: withthegrid/platform#866

feat: 866 any operator in analytics queries

---

src/models/fields/base-field-configuration.ts

part of https://github.com/withthegrid/platform/issues/1014

feat: initialValue for switch, radio and checkbox form field configs

---

src/models/analytics-query.ts

is required by: https://github.com/withthegrid/platform/pull/998
refs withthegrid/platform#932

feat: group by hour in analytics

---

src/routes/device-type/add.ts
src/routes/device-type/get.ts
src/routes/device-type/update.ts
src/routes/supplier-certificate/add.ts
src/routes/supplier-certificate/get.ts
src/routes/supplier-certificate/update.ts
src/routes/supplier-report-type/add.ts
src/routes/supplier-report-type/get.ts
src/routes/supplier-report-type/update.ts
src/routes/supplier-webhook/add.ts
src/routes/supplier-webhook/get.ts
src/routes/supplier-webhook/update.ts

refs: withthegrid/platform#828
is part of https://github.com/withthegrid/platform/pull/1035 but may be merged independently.

feat: 828 enforce event handlers have max length

---

src/index.ts
src/routes/graph/get-edge.ts
src/routes/graph/get-grid.ts
src/routes/graph/get-pin-group.ts

refs withthegrid/platform#763
is required by: https://github.com/withthegrid/platform/pull/1036

feat: 763 no photo files in response of edge or pingroup

---

src/routes/suggestions/find.ts

is required by: https://github.com/withthegrid/platform/pull/1004
refs: withthegrid/platform#944

fix 944 device table shows monitoring environments with attached devices

---

src/models/user.ts
src/routes/issue-comment/update.ts
src/routes/issue/add-comment.ts
src/routes/issue/add.ts
src/routes/issue/find.ts
src/routes/issue/get.ts
src/routes/issue/update.ts
src/routes/settings/find-log.ts
src/routes/settings/update.ts
src/routes/user/add.ts

Is required for https://github.com/withthegrid/platform-client/pull/924

#782 - Limited Name to 255 characters

---

src/routes/settings/update.ts

Is required for https://github.com/withthegrid/platform-client/pull/925

#855 - Limited password length

---

package-lock.json
package.json

closes #145 #144 #143 #142 #141

chore(deps): minimist

---

package-lock.json
package.json

chore(deps): redoc-cli, eslint-parser and plugin

---

.eslintrc.js
documentation/index.ts
package.json
tsconfig.esm.json

* droppping "eslint-disable-next-line" comments
* eslint for ./documentation

fix: documentation linting

---

src/models/analytics/analytics-tables.ts

fix: error in analytics dashboard with edge form fields

---

README.md

fix: trigger a new release

---

src/models/analytics/analytics-tables.ts

fixes: #183
requires: https://github.com/withthegrid/platform-client/pull/1147

Fix 183 fix selecting grid pin group as column in analytics

---

package-lock.json
package.json

chore(deps): axios

---

src/models/analytics-query.ts

required by: https://github.com/withthegrid/platform-client/pull/1205
refs: withthegrid/platform-client#1151

fix: add type information for form fields in analytics

---

src/comms/index.ts

fix: axios error

---

src/models/string-or-translations.ts
src/models/translations.ts

required by: https://github.com/withthegrid/platform/pull/1298
refs: withthegrid/platform#1255

feat: step 4 migration for multi-language support connectivity

---

src/models/export-request.ts
src/routes/settings/add-export.ts

Is required for https://github.com/withthegrid/platform-client/pull/1357

feat(exports): export location graph

---

.github/workflows/ci-cd.yml
src/models/analytics/analytics-tables.ts
test/analytics/analytics-tables.test.ts

Is a part of https://github.com/withthegrid/platform-client/pull/1419

feat(analytics): imroved UI of filtered aggregated column

---

src/routes/graph/index.ts
src/routes/graph/routes.ts
src/routes/graph/update-grid.ts
src/routes/graph/update-pin-groups.ts

Is required for https://github.com/withthegrid/platform-client/pull/1458

feat(groups): added possibility to move all locations of group to another map later

---

src/models/analytics-visualisation.ts

Is required fro https://github.com/withthegrid/platform-client/pull/1555

feat(analytics): allowed to set yMin and yMax for line charts

---

src/models/analytics/analytics-tables.ts

refs: withthegrid/platform#878

chore: clarify naming for the user who updated a device link.

---

src/commons/link-replacer.ts

fixes withthegrid/platform#1643

fix: only part of conditierapport in issue hyperlinked

---

src/models/analytics/analytics-tables.ts

Refs: https://github.com/withthegrid/platform-client/issues/1640
Is required by: https://github.com/withthegrid/platform/pull/1789
Is required by: https://github.com/withthegrid/platform-client/pull/1771

feat(analytics): add issueAssignedUser table

---

src/models/import-request.ts
src/routes/import-request/generate-template.ts

required by: https://github.com/withthegrid/platform-client/pull/1830
required by: https://github.com/withthegrid/platform/pull/1846
refs: withthegrid/platform-client#1822

fix(measurement imports): user experience enhancements

---

src/routes/quantity/find.ts

part of withthegrid/platform#1845

fix: drop environmentReportTypeHashIds from quantity.find

---

src/routes/report/get-id-by-timeseries-point.ts
src/routes/report/index.ts
src/routes/report/routes.ts

required by: https://github.com/withthegrid/platform/pull/1927
required by: https://github.com/withthegrid/platform-client/pull/1924
refs: [1871](https://github.com/withthegrid/platform/issues/1871)

feat: report hashid missing when clicking in graph

---

src/routes/chart/get-panels.ts
src/routes/chart/index.ts
src/routes/chart/routes.ts
src/routes/chart/update-panels.ts

@Arinono 
refs withthegrid/platform-client#2010
used by [private sdk](https://github.com/withthegrid/platform-sdk-private/pull/275)
used by [client](https://github.com/withthegrid/platform-client/pull/2093)
used by [platform](https://github.com/withthegrid/platform/pull/2043)
add bulk get and update panels endpoints

feat(panels): get and update multiple panels
